### ISSUE TITLE
Immer problem

### ISSUE THREAD

**Issue by AtharvaKoli06** [immerjs/immer#1093]
@reduxjs_toolkit.js?v=be281d0e:55 Uncaught (in promise) Error: [Immer] Immer only supports setting array indices and the 'length' property
    at die (@reduxjs_toolkit.js?v=be281d0e:55:11)
    at arrayTraps.set (@reduxjs_toolkit.js?v=be281d0e:479:5)
    at getAllAttendence.slice.jsx:30:13
    at @reduxjs_toolkit.js?v=be281d0e:1795:20
    at Immer2.produce (@reduxjs_toolkit.js?v=be281d0e:547:20)
    at @reduxjs_toolkit.js?v=be281d0e:1794:18
    at Array.reduce (<anonymous>)
    at reducer (@reduxjs_toolkit.js?v=be281d0e:1775:25)
    at reducer (@reduxjs_toolkit.js?v=be281d0e:2207:14)
    at combination (chunk-RJJ6DPM5.js?v=be281d0e:298:31)
    at redux-persist.js?v=be281d0e:419:20
    at hu (<anonymous>:3:1043)
    at yu (<anonymous>:3:1331)
    at <anonymous>:3:4637
    at Object.dispatch (chunk-RJJ6DPM5.js?v=be281d0e:147:22)
    at Object.s [as dispatch] (<anonymous>:3:5093)
    at dispatch (@reduxjs_toolkit.js?v=be281d0e:1624:22)
    at auth.jsx:39:10
    at @reduxjs_toolkit.js?v=be281d0e:1117:12
    at @reduxjs_toolkit.js?v=be281d0e:1398:34

**Comment by mweststrate** [comment]
Please try again by following the issue template. By the looks of it you are assigning to a non-numeric property of an array, which, as the error indicates, is not supported.
