### ISSUE TITLE
Immer 7.0.9 not support React Native 0.63.3 hermes engine in release build

### ISSUE THREAD

**Issue by someok** [immerjs/immer#679]
## 🐛 Bug Report

If I `enableHermes: true` in React Native, the release apk will crash. the logcat show:

```
2020-10-03 18:59:37.149 10786-10900/? E/AndroidRuntime: FATAL EXCEPTION: T-toStch
    Process: com.example, PID: 10786
    com.facebook.react.common.JavascriptException: Error: [Immer] minified error nr: 19 ES5. Find the full error at: https://bit.ly/3cXEKWf, js engine: hermes, stack:
    t@1:1790676
    A@1:1792023
    C@1:1793708
    anonymous@1:1803170
    anonymous@1:1788899
    anonymous@1:1789036
    onEnterRoom@1:1825895
    anonymous@1:1824905
    value@1:87033
    value@1:81249
    anonymous@1:79889
    value@1:80845
    value@1:79847
    
        at com.facebook.react.modules.core.ExceptionsManagerModule.reportException(ExceptionsManagerModule.java:12)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.facebook.react.bridge.JavaMethodWrapper.invoke(JavaMethodWrapper.java:18)
        at com.facebook.react.bridge.JavaModuleWrapper.invoke(JavaModuleWrapper.java:2)
        at com.facebook.react.bridge.queue.NativeRunnable.run(Native Method)
        at android.os.Handler.handleCallback(Handler.java:900)
        at android.os.Handler.dispatchMessage(Handler.java:103)
        at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:1)
        at android.os.Looper.loop(Looper.java:219)
        at com.facebook.react.bridge.queue.MessageQueueThreadImpl$4.run(MessageQueueThreadImpl.java:8)
        at java.lang.Thread.run(Thread.java:929)
```

## Environment

- [X] Immer: 7.0.9
- [X] React Native: 0.63.3

**Comment by mweststrate** [comment]
If you follow the link in the error message, find error no. 19, and then check the Immer installation instructions, you'll should be able to solve your issue.

**Comment by someok** [comment]
@mweststrate Thanks, I found this:

> By default produce tries to use proxies for optimal performance. However, on older JavaScript engines Proxy is not available. For example, when running Microsoft Internet Explorer or React Native (if < v0.59 or when using the Hermes engine) on Android. In such cases, Immer will fallback to an ES5 compatible implementation which works identically, but is a bit slower.

> Since version 6, support for the fallback implementation has to be explicitly enabled by calling enableES5()

**Comment by peterkuiper** [comment]
@mweststrate There is no error 19 in https://github.com/immerjs/immer/blob/master/src/utils/errors.ts.

**Comment by mweststrate** [comment]
@peterkuiper look under the correct tag, not master
